version: '3.7'
services:
  #run: docker-compose down --volumes to refresh everything
  postgresahma-shop-postgres:
    container_name: postgresahma-shop-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_USER=ahabdu
#      - POSTGRES_DB=store_tracker
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5439:5432'
    volumes:
      - postgresahma-shop-postgres-volume:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./migrations/down.sql:/docker-entrypoint-initdb.d/down.sql
      # copy the sql script to fill tables
      - ./migrations/up.sql:/docker-entrypoint-initdb.d/up.sql
volumes:
  postgresahma-shop-postgres-volume: